# Site settings
title: "UAPGerb Video Wiki"
description: "Automatically maintained wiki for @UAPGerb YouTube channel with searchable transcripts"
baseurl: ""
url: "https://username.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Exclude files from processing
exclude:
  - scripts/
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock

# Site navigation
header_pages:
  - index.md
  - about.md

# Social links
github_username: username
youtube_channel: "@UAPGerb"

# SEO
twitter:
  username: username
  card: summary

# Analytics (optional)
google_analytics: # Add your GA tracking ID here if desired

