name: Sync and Publish
on:
  schedule:
    - cron: '7 * * * *'
  workflow_dispatch: {}
permissions:
  contents: write
concurrency:
  group: sync-and-publish
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          pip install mkdocs mkdocs-material
      - name: Sync transcripts (all videos)
        run: python scripts/sync.py
      - name: Commit transcripts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/transcripts
          git commit -m "chore: update transcripts" || echo "No changes"
          git push origin HEAD:main
      - name: Build site
        run: mkdocs build --strict
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
